### PR TITLE
Fully support the package.json browser spec

### PR DESCRIPTION
**Pull request by sickboy**
Add support for browser field being an object as per https://github.com/defunctzombie/package-browser-field-spec
example usage in: https://github.com/Reactive-Extensions/RxJS/blob/master/package.json

### CODE REVIEW

**Comment by wesleyb-io** [comment]
This P.R. **does not solve another potential value** for the `browser` property of a `package.json`; the following Github issues reveal the potential existence of value `buffer: false`:

- https://github.com/jaredallard/nexe/issues/148#issuecomment-156815985
- https://github.com/aurelia/webpack-plugin/issues/12#issuecomment-205042657

I cannot find documentation on `buffer: false`.

- Is `buffer: false` an invalid value?
- Is `buffer: false` a value that should be supported?
- If `buffer: false` is a valid value, how should it be supported?

**Comment by masterpoi** [comment]
Using my in-head javascript compiler, this PR does not work with this file: https://github.com/mapbox/mapbox-gl-js/blob/master/package.json

**Comment by EisenbergEffect** [comment]
This seems like something nice to support. However, I agree with @masterpoi. I think there may be a few errors. @sickboy Would you mind looking back over the code. I think that if there is a browser property but no main, then the code will fail. Also if both exists but no lookup is found in browser, I think it will fail as well. There may be other scenarios. Perhaps @masterpoi can add some notes as well.

**Comment by masterpoi** [comment]
I was trying to use mapbox-gl-js in a project with aurelia & webpack and had the original code fail on the dictionary lookup. Then i saw this PR, but didn't think it would work either. If i read the spec correctly, i think line 27 of the commit should be  

`main = vendorPkg.browser[vendorPkg.main] || main;`

Also all future references to the keys of the object in the browser field should be redirected to their respective values, so i guess they need to be in the context map as well?

(For my mapbox-gl issue, i switched to jspm 0.17, and loaded mapbox as a single bundle, mainly because of another issue where i need to dynamically load aurelia components from other domains, and that is something that is not supported by webpack)

**Comment by EisenbergEffect** [comment]
Would anyone like to submit an updated PR?

**Comment by EisenbergEffect** [comment]
Would someone like to review this PR? https://github.com/aurelia/webpack-plugin/pull/20
Is this a more "correct" implementation?

**Comment by EisenbergEffect** [comment]
There's a second PR that seems more correct. We'll follow up there esp. since the original author hasn't responded.

**Pull request closed without merging**
