### PR TITLE
fix: fix css bundle on webpack v5.52.0+

### PR DESCRIPTION
**Pull request by 3cp**

### CODE REVIEW

**Comment by 3cp** [comment]
Note the html-requires-loader.ts can actually be unit tested.

**Comment by bigopon** [comment]
@3cp thanks. At the moment I'm doing a combo of manual and smoke testing. That should be enough for now. If there's anything tricky, I'll resort to an e2e tool probably.

**Comment by bigopon** [comment]
It seems we are good to go, thanks heap @3cp !

**Comment by 3cp** [comment]
Hopefully webpack would not ship breaking change too soon.

**Comment by bigopon** [comment]
From the look of v4 and v5, it'll probably take awhile. They seem to move with a lot of caution. We're also quite prepared, since I've resolved all the warnings in our plugin. 🤞

**Pull request merged**
