### PR TITLE
 fix(webpack-plugin): Windows specific paths fix

### PR DESCRIPTION
**Pull request by marktaling**
fixed an issue where paths weren't correctly normalized, causing the resulting bundle to contain moduleId's as integers instead of their names when packed on a windows machine

### CODE REVIEW

**Comment by marktaling** [comment]
I've corrected the test which was already present, by current Chai implementation it did not test anything. As the existing test did not verify the content of the bundle, I haven't added a test for this change. (Did try for a bit but haven't managed to load the bundle into the test.)

**Comment by niieani** [comment]
@marktaling this looks fine, although we have v2 of this plugin coming out in a few days https://github.com/aurelia/webpack-plugin/pull/88 so I'm not sure if we still want to release this fix ( CC: @EisenbergEffect ? ). Also, the person releasing to NPM is the one to bump version and commit the `dist` files.

**Comment by marktaling** [comment]
I will remove the version number and dist files, I had to add them to create a local package and see if it also works in our production scenarios.

I understand v2 is on it's way. However, we're currently running v1 and have an issue where the output isn't identical depending on the OS the developer is using. This leads to some nasty inconsistencies when using aurelia and webpack to develop "modular" applications.
As such, I would really appreciate it if this patch could still be released for those of us who are not yet ready to upgrade to v2.

**Comment by niieani** [comment]
Sure, I understand. @EisenbergEffect let's do one more v1 release before v2 then 👍

**Comment by EisenbergEffect** [comment]
@niieani Ok, so merge this and then do a 1.x release?

**Comment by niieani** [comment]
Yes. 👍

**Comment by tbreffni** [comment]
This change appears to have broken our app - downgrading back to 1.2.1 resolved the issue. Not quite sure why this change specifically broke us, but if it's useful here is the error we kept getting. This is on a Windows machine:

```
Message: Cannot set property 'viewSlot' of undefined
Inner Error Stack:
TypeError: Cannot set property 'viewSlot' of undefined
    at new e (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:6:10433)
    at Object.invoke (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:7:29851)
    at e.t.InvocationHandler.e.invoke (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:7:29767)
    at e.t.Container.e.invoke (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:8:1231)
    at e.t.StrategyResolver.e.get (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:7:27245)
    at e.t.Container.e.get (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:8:548)
    at Object.v (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:7:24549)
    at e.t.InvocationHandler.e.invoke (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:7:29767)
    at e.t.Container.e.invoke (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:8:1231)
    at e.t.StrategyResolver.e.get (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:7:27245)
    at e.t.Container.e._get (https://localhost:3455/assets/aurelia/bundles/aurelia.bundle.js?Development:8:711)
```

I can open a separate Github issue for this if that works better.

**Pull request merged**
