### PR TITLE
fix "Can't resolve 'bundle'" issue

### PR DESCRIPTION
**Pull request by jinwangchina**

### CODE REVIEW

**Comment by jods4** [comment]
Thanks for this submission, webpack 2.0 does indeed need `-loader` by default, this is a breaking change from webpack 1.0.

As we are close to publishing a complete rewrite of the plugins for webpack 2.2 anyway, I'm not sure if we want to merge that PR or skip it.... @niieani ?

**Comment by niieani** [comment]
@EisenbergEffect If we want to publish the old webpack-plugin as `1.2.1` and the new one as `2.0.0-beta` at the same time (in two steps) then I'd be down with merging this too.

**Comment by EisenbergEffect** [comment]
Ok, just to make sure I understand the plan. You want me to merge this and then make a 1.x release. Then merge #88 and make the 2.x release. Is that correct?

**Comment by niieani** [comment]
@EisenbergEffect this would be ideal, yes, since it's a bug-fix for those running the v1 stack. But if it's too much work, we can also just focus on providing v2 ASAP and getting all those affected migrated.

**Comment by EisenbergEffect** [comment]
It's no problem. I just wanted to make sire I did the right thing.

**Pull request merged**
