### PR TITLE
fix(getPAL): use browser-pal for electron-renderer

### PR DESCRIPTION
**Pull request by MeirionHughes**

### CODE REVIEW

**Comment by niieani** [comment]
It might make sense to also use urelia-pal-nodejs for electron renderer (it should also work).

**Comment by jods4** [comment]
I was suggested as reviewer but honestly guys I have no idea about `electron` stuff.
I'm wondering if `aurelia-pal-browser` shouldn't be the default, though....

I'm not using Electron at all, so if someone with more experience tells me it's the good choice, then let's merge.

**Comment by MeirionHughes** [comment]
the renderer thread is chromium; I don't see why you'd want to use pal-nodejs within what is effectively chrome. for one you get full SVG support...

**Comment by MeirionHughes** [comment]
here is working repo btw: https://github.com/MeirionHughes/aurelia-webpack-electron its working flawlessly so far. I noticed you can override the pal via the opts (better late than never).

**Comment by niieani** [comment]
@MeirionHughes 

> I don't see why you'd want to use pal-nodejs within what is effectively chrome

You can use `pal-nodejs` in Electron to effectively skip any build/compilation steps. Since Electron is Node + Chromium, you get the best of both worlds. This way you can use Aurelia from pure JavaScript or pure TypeScript (if you use something like `ts-node/register` or even ESNext when using `babel-register`). NodeJS effectively becomes the loader and no bundling is necessary. Of course, HMR won't work this way at the moment (it would need a plugin which watches files for changes), but it should be possible.

**Comment by MeirionHughes** [comment]
> You can use pal-nodejs in Electron to effectively skip any build/compilation steps.

would that not imply you are not using this webpack plugin?

**Comment by niieani** [comment]
@MeirionHughes ah, yes! Forgot we're in the webpack-plugin context. So in that case, this totally PR makes sense. Let's merge it!

**Pull request merged**
