### PR TITLE
Added webpack plugin code

### PR DESCRIPTION
**Pull request by martijnboland**
This is the first PR for Aurelia webpack support, the webpack plugin. I've removed the gulp build files, because these are not required for this module. It's node-only without any build step. It should only be published to NPM.

Tested locally with npm pack and installed the local package into a local skeleton-webpack app.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@martijnboland This is going to be great. Thank you for this work! I just realized I need one more thing from you before we can merge this. Can you sign our CLA? https://docs.google.com/a/durandal.io/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

Thanks!

**Comment by martijnboland** [comment]
Signed!

**Comment by EisenbergEffect** [comment]
Thanks!

**Comment by EisenbergEffect** [comment]
Excellent!

**Comment by martijnboland** [comment]
Expect another PR for the plugin because yesterday I noticed that the VS 2015 task runner explorer comes with an older Node version that doesn't support ES6 string functions like endsWith. Going to make this plugin completely ES5 for max. compatibility.

**Comment by EisenbergEffect** [comment]
Thank you. I appreciate this!

**Pull request merged**
